publishEnabled=false

# Minecraft and Forge params
neoVersion=21.1.221
neoVersionRange=[21.1.0,)
parchmentVersion=2024.11.17
mcVersion=1.21.1
mcVersionRange=[1.21.1, 1.22)

# Mod params
modGroup=org.dreamfinity
modId=dsgl-demo
modName=dsgl-demo
modArchivesName=dsgl-demo
modAuthor=Veritaris
modIcon=
modDescription=Dreamfinity Simple GUI Library Demo
modCredits=Veritaris
buildVersion=1
modVersion=0.0.1

# Mod dev params
isClientBuild=false
clientRunArgs="--username" "Dreamfinity"
serverRunArgs="--no-gui"
hotReload=true
msdfDebug=false
msdfDebugDecorations=false
msdfDebugPerformance=false
rebuildTrace=false
perfDebug=false
dsglOverlayDebug=true
dsglOverlayControls=true

startParameter.offline=true

# Publishing params
publishProjectDepsOnly=true
