package org.dreamfinity.dsgl.core.colorpicker

import org.dreamfinity.dsgl.core.DsglColors

data class ColorPickerStyle(
    val padding: Int = 8,
    val panelBackgroundColor: Int = 0xFF1E252F.toInt(),
    val panelBorderColor: Int = 0xFF5A6C80.toInt(),
    val panelShadowColor: Int = 0x7A0C1118,
    val textColor: Int = DsglColors.WHITE,
    val mutedTextColor: Int = 0xFF9CB1C8.toInt(),
    val inputBackgroundColor: Int = 0xFF263240.toInt(),
    val inputBorderColor: Int = 0xFF607A95.toInt(),
    val inputActiveBorderColor: Int = 0xFFA8D6FF.toInt(),
    val buttonBackgroundColor: Int = 0xFF2E3A49.toInt(),
    val buttonHoverColor: Int = 0xFF3A4A5D.toInt(),
    val buttonActiveColor: Int = 0xFF496178.toInt(),
    val checkerLightColor: Int = 0xFFCCD4DC.toInt(),
    val checkerDarkColor: Int = 0xFF8F9AA5.toInt(),
    val thumbOutlineColor: Int = 0xFFFFFFFF.toInt(),
    val thumbShadowColor: Int = 0xAA000000.toInt(),
    val recentGridBorderColor: Int = 0xFF4A5C70.toInt(),
    val fontSize: Int = 24,
    val modeButtonHeight: Int = 22,
    val modeSelectHeight: Int = 22,
    val modeSelectWidth: Int = 108,
    val modeSelectMinWidth: Int = 96,
    val modeOptionHeight: Int = 20,
    val modeRowGap: Int = 6,
    val rgbOrderLabelWidth: Int = 52,
    val rgbOrderLabelGap: Int = 4,
    val colorFieldHeight: Int = 136,
    val sliderHeight: Int = 14,
    val swatchHeight: Int = 24,
    val inputHeight: Int = 24,
    val inputLabelWidth: Int = 16,
    val inputLabelGap: Int = 4,
    val eyedropperGridSize: Int = 11,
    val eyedropperCellSize: Int = 8,
    val eyedropperGapToCursor: Int = 14,
    val eyedropperTooltipWidth: Int = 228,
    val eyedropperTooltipHeight: Int = 52,
    val eyedropperOverlayBackgroundColor: Int = 0xF01A222C.toInt(),
    val eyedropperOverlayBorderColor: Int = 0xFF7F96AD.toInt(),
    val eyedropperCenterBorderColor: Int = 0xFFFFFFFF.toInt(),
    val rowGap: Int = 6,
    val recentCellSize: Int = 14,
    val recentCellGap: Int = 2,
    val minWidth: Int = 280,
    val eyedropperGridOverlayEnabled: Boolean = true,
    val eyedropperGridOverlayColor: Int = 0x22FFFFff.toInt(),
)
