package org.dreamfinity.dsgl.core.select

import org.dreamfinity.dsgl.core.DsglColors

data class SelectStyle(
    val viewportPadding: Int = 6,
    val panelPaddingX: Int = 4,
    val panelPaddingY: Int = 4,
    val rowPaddingX: Int = 6,
    val rowPaddingY: Int = 3,
    val rowGap: Int = 1,
    val separatorHeight: Int = 6,
    val separatorInsetX: Int = 4,
    val groupIndentX: Int = 10,
    val markerColumnWidth: Int = 10,
    val markerGap: Int = 6,
    val minPanelWidth: Int = 120,
    val maxPanelHeightPadding: Int = 10,
    val maxPanelWidthPadding: Int = 10,
    val wheelStepRows: Int = 3,
    val typeAheadResetMs: Long = 700L,
    val fontId: String? = null,
    val fontSize: Int? = null,
    val panelBackgroundColor: Int = 0xFF1E2530.toInt(),
    val panelBorderColor: Int = 0xFF5B6A78.toInt(),
    val panelShadowColor: Int = 0x6A0E1622,
    val optionHoverBackgroundColor: Int = 0xFF35506A.toInt(),
    val optionSelectedBackgroundColor: Int = 0xFF2C4156.toInt(),
    val optionTextColor: Int = DsglColors.WHITE,
    val disabledTextColor: Int = 0xFF8C98A4.toInt(),
    val groupTextColor: Int = 0xFFB6C2CE.toInt(),
    val separatorColor: Int = 0xFF4C5C6D.toInt(),
    val markerColor: Int = 0xFF8BE39A.toInt(),
    val scrollbarGap: Int = 2,
    val scrollbarWidth: Int = 6,
    val scrollbarMinThumbHeight: Int = 12,
    val scrollbarTrackColor: Int = 0x553B4A5A,
    val scrollbarThumbColor: Int = 0xAA8FA2B6.toInt(),
    val arrowGlyph: String = "\u25BE",
    val checkGlyph: String = "\u2713",
    val openDurationMs: Long = 130L,
    val closeDurationMs: Long = 100L,
    val openStartScale: Float = 0.985f,
    val openStartOffsetYPx: Float = -4f
)
