publishEnabled=false

# Minecraft and Forge params
gameVersion=1.7.10
forgeVersion=10.13.4.1614

# Mod params
modGroup=org.dreamfinity
modId=dsgl-demo
modName=dsgl-demo
modArchivesName=dsgl-demo
modAuthor=Veritaris
modIcon=
modDescription=Dreamfinity Simple GUI Library Demo
modCredits=Veritaris
buildVersion=1
modVersion=0.0.1

# Mod dev params
isClientBuild=false
clientRunArgs="--username" "Dreamfinity"
serverRunArgs="--no-gui"
hotReload=true
msdfDebug=false
msdfDebugDecorations=false
msdfDebugPerformance=false
rebuildTrace=false
perfDebug=false
dsglOverlayDebug=true
dsglOverlayControls=true
dsglColorPickerDebugCounters=false

startParameter.offline=true

# Publishing params
publishProjectDepsOnly=true
